/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import trandpl.dao.UserDao;
import trandpl.pojo.CurrentUser;
import trandpl.pojo.UserPojo;

/**
 *
 * @author HP
 */
public class LoginFrame extends javax.swing.JFrame {

    private String userId;
    private String password;
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private boolean validateInputs(){
        userId=txtMail.getText().trim();
       char []pwd=txtPasswordField.getPassword();
        if(userId.isEmpty()||pwd.length==0)
            return false;
        password=String.valueOf(pwd);
        return true;      
    }
    private String validateUser(){
        if(jrbAdmin.isSelected())
           return "Admin";
        else if(jrbHr.isSelected())
            return "Hr";
        else if(jrbUser.isSelected())
            return "Student";
        else
            return null;
    }
   
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtPasswordField = new javax.swing.JPasswordField();
        jrbAdmin = new javax.swing.JRadioButton();
        jrbHr = new javax.swing.JRadioButton();
        jrbUser = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homePage.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1084, 625));
        setSize(new java.awt.Dimension(1084, 625));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel2.setText("Email or User Id :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 120, 150, 30);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel1.setText("Password :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 200, 110, 20);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel3.setText("Select User Type:-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 340, 150, 30);

        txtMail.setBackground(new java.awt.Color(173, 192, 234));
        txtMail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMail.setBorder(null);
        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });
        getContentPane().add(txtMail);
        txtMail.setBounds(120, 160, 400, 30);

        txtPasswordField.setBackground(new java.awt.Color(173, 192, 234));
        txtPasswordField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPasswordField.setBorder(null);
        txtPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(txtPasswordField);
        txtPasswordField.setBounds(120, 240, 400, 30);

        buttonGroup1.add(jrbAdmin);
        jrbAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbAdmin.setText("Admin");
        getContentPane().add(jrbAdmin);
        jrbAdmin.setBounds(100, 390, 90, 25);

        buttonGroup1.add(jrbHr);
        jrbHr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbHr.setText("Company HR");
        getContentPane().add(jrbHr);
        jrbHr.setBounds(220, 390, 120, 25);

        buttonGroup1.add(jrbUser);
        jrbUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbUser.setText("User");
        getContentPane().add(jrbUser);
        jrbUser.setBounds(380, 390, 90, 25);

        btnLogin.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(100, 470, 160, 27);

        btnSignUp.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp);
        btnSignUp.setBounds(370, 470, 150, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_1147698449.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 150, 440, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_1147698449.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 230, 440, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(100, 430, 420, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(100, 300, 420, 20);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homePage.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel5)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1090, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(validateInputs()==false){
            JOptionPane.showMessageDialog(null,"please fill all the fields","Error!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String type=validateUser();
        if(type==null){
            JOptionPane.showMessageDialog(null,"please select user type ","Error!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        UserPojo user=new UserPojo();
        user.setUserid(userId.toUpperCase());
        user.setPassword(password);
        user.setType(type);
        try
        {
            boolean result=UserDao.validateUser(user);
            if(result){
                if(CurrentUser.getType().equals("Admin")) {
                        JOptionPane.showMessageDialog(null,"Welcome Admin "+CurrentUser.getName(),"Success",JOptionPane.INFORMATION_MESSAGE);
                        new AdminOptionsFrame().setVisible(true);
                        this.dispose();
                }
                else if(CurrentUser.getType().equals("HR")){
                        //
                }
                else if(CurrentUser.getType().equals("Student")){
                    //
                }
                }else {
                        JOptionPane.showMessageDialog(null,"Invalid User Id and Password or UserType ","Error!",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error!","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
           
        }
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFieldActionPerformed

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton jrbAdmin;
    private javax.swing.JRadioButton jrbHr;
    private javax.swing.JRadioButton jrbUser;
    private javax.swing.JTextField txtMail;
    private javax.swing.JPasswordField txtPasswordField;
    // End of variables declaration//GEN-END:variables
}
